version: "3.7"
services:
    pg:
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: products-api
        volumes:
            - .pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
    web:
        container_name: productsapi
        build: .
        ports: 
            - "3001:3001"
        depends_on: 
            - pg
    pgadmin:
        image: dpage/pgadmin4
        depends_on: 
            - pg 
        ports: 
            - "5555:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: jose@admin.org
            PGADMIN_DEFAULT_PASSWORD: postgres
        restart: unless-stopped
      